# Generated by Django 4.1.2 on 2024-06-05 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='obra',
            fields=[
                ('idObra', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='id Arbeit')),
                ('nombre', models.CharField(max_length=30, verbose_name='Name der Arbeit')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Description')),
                ('autor', models.CharField(max_length=50, verbose_name='Name des Autors')),
                ('anio', models.CharField(max_length=4, verbose_name='Jahr der Arbeit')),
                ('disponible', models.BooleanField(default=False, verbose_name='Disponibilidad/Verfügbarkeit')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes', verbose_name='Fotografie')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria', verbose_name='Kategorie')),
            ],
        ),
    ]
