# Generated by Django 4.1.2 on 2024-06-05 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='disponible',
        ),
    ]
