# Generated by Django 4.1.2 on 2024-06-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_obra_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Available'),
        ),
    ]
