# Generated by Django 5.0.6 on 2024-06-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_obra_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='precio',
            field=models.IntegerField(default=0, verbose_name='Precio'),
        ),
    ]
