# Generated by Django 5.0.6 on 2024-06-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_obra_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
