# Generated by Django 5.0.6 on 2024-06-23 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_obra_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('codigo', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Numero_Boleta')),
                ('fecha', models.DateField()),
                ('monto', models.IntegerField(default=0, verbose_name='Monto_Boleta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('codDetalle', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Codigo_Detalle_Boleta')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('valorTotal', models.IntegerField(default=0, verbose_name='Valor_Total')),
                ('codigo_Boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.boleta', verbose_name='Codigo_Boleta')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.obra', verbose_name='ID_Producto')),
            ],
        ),
    ]
