# Generated by Django 5.0.6 on 2024-06-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_boleta_detalleboleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
    ]
