# Generated by Django 5.0.6 on 2024-06-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_obra_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='available',
        ),
        migrations.AlterField(
            model_name='boleta',
            name='monto',
            field=models.IntegerField(verbose_name='Monto_Boleta'),
        ),
        migrations.AlterField(
            model_name='detalleboleta',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='autor',
            field=models.CharField(max_length=99, verbose_name='Name des Autors'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='precio',
            field=models.IntegerField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='stock',
            field=models.IntegerField(verbose_name='Stock'),
        ),
    ]
