# Generated by Django 5.0.6 on 2024-06-25 05:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_obra_available_alter_boleta_monto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='detalleboleta',
            name='codDetalle',
        ),
        migrations.RemoveField(
            model_name='detalleboleta',
            name='codigo_Boleta',
        ),
        migrations.RemoveField(
            model_name='detalleboleta',
            name='idProducto',
        ),
        migrations.RemoveField(
            model_name='detalleboleta',
            name='valorTotal',
        ),
        migrations.AddField(
            model_name='boleta',
            name='fechaCompra',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='boleta',
            name='id_boleta',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='boleta',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detalleboleta',
            name='id_boleta',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='core.boleta'),
        ),
        migrations.AddField(
            model_name='detalleboleta',
            name='id_detalle_boleta',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='detalleboleta',
            name='id_obra',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.obra'),
        ),
        migrations.AddField(
            model_name='detalleboleta',
            name='subtotal',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detalleboleta',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='obra',
            name='precio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio'),
        ),
    ]
