# Generated by Django 5.0.6 on 2024-06-26 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_customuser_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleboleta',
            name='id_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
