# Generated by Django 5.0.6 on 2024-06-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_detalleboleta_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleboleta',
            name='id_user',
        ),
    ]
