# Generated by Django 5.0.6 on 2024-07-11 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_detalleboleta_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='id_boleta',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='total',
        ),
        migrations.AddField(
            model_name='boleta',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='boleta',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleta',
            name='transaccion_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='boleta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='fechaCompra',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='BoletaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('fechaAdd', models.DateTimeField(auto_now_add=True)),
                ('boleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.boleta')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.obra')),
            ],
        ),
        migrations.DeleteModel(
            name='DetalleBoleta',
        ),
    ]
