# Generated by Django 5.0.6 on 2024-07-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_direccionenvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
