# Generated by Django 5.0.6 on 2024-07-12 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_boleta_total'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoletaItem',
            new_name='DetalleCompra',
        ),
    ]
