# Generated by Django 5.0.6 on 2024-07-12 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_boletaitem_detallecompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='transaccion_id',
        ),
    ]
