# Generated by Django 5.0.6 on 2024-07-12 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_boleta_transaccion_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetalleCompra',
            new_name='BoletaItem',
        ),
        migrations.RenameField(
            model_name='boleta',
            old_name='fechaCompra',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='boletaitem',
            old_name='fechaAdd',
            new_name='fechaCompra',
        ),
        migrations.RenameField(
            model_name='direccionenvio',
            old_name='fechaAdd',
            new_name='fecha',
        ),
        migrations.AlterField(
            model_name='boleta',
            name='usuario',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
