# Generated by Django 5.0.6 on 2024-07-12 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rename_detallecompra_boletaitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boletaitem',
            old_name='fechaCompra',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='boletaitem',
            old_name='producto',
            new_name='product',
        ),
        migrations.DeleteModel(
            name='DireccionEnvio',
        ),
    ]
