# Generated by Django 5.0.6 on 2024-07-12 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_fechacompra_boletaitem_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletaitem',
            name='boleta',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.boleta'),
        ),
        migrations.AlterField(
            model_name='boletaitem',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='boletaitem',
            name='product',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.obra'),
        ),
    ]
