# Generated by Django 5.0.6 on 2024-07-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_boletaitem_boleta_alter_boletaitem_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='total',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
