# Generated by Django 5.2.1 on 2025-05-11 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_boleta_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceMensual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='idBalanceMensual')),
                ('fecha', models.DateTimeField(null=True, verbose_name='FechaBalanceMensual')),
                ('BalancesMensual', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='BalanceMensual')),
                ('totalVentas', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='TotalVentas')),
            ],
        ),
        migrations.CreateModel(
            name='InformeDesemp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='idInformeDesemp')),
                ('fecha', models.DateTimeField(null=True, verbose_name='FechaInformeDesemp')),
                ('descripcion', models.CharField(max_length=255, verbose_name='DescripcionInformeDesemp')),
            ],
        ),
        migrations.CreateModel(
            name='InformeMensual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='idInformeMensual')),
                ('fecha', models.DateTimeField(null=True, verbose_name='FechaInformeMensual')),
                ('descripcion', models.CharField(max_length=255, verbose_name='DescripcionInformeMensual')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='idTipoUser')),
                ('nombreTipoUser', models.CharField(max_length=15, verbose_name='nombreTipoUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='usuario',
        ),
        migrations.AddField(
            model_name='boleta',
            name='idUser',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='idUsuario'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='complete',
            field=models.BooleanField(default=False, null=True, verbose_name='Complete'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='idCompras')),
                ('cantidad', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Cantidad')),
                ('total', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Total')),
                ('fecha', models.DateTimeField(null=True, verbose_name='Fecha')),
                ('idBoleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.boleta', verbose_name='idBoleta')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='idPedido')),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('enviado', 'enviado'), ('entregado', 'entregado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha')),
                ('idCompra', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.compra', verbose_name='idCompra')),
                ('idUser', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='idUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='idProducto')),
                ('nombre', models.CharField(max_length=50, verbose_name='Name der Arbeit')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Description')),
                ('marca', models.CharField(max_length=99, verbose_name='Markenname')),
                ('anio', models.CharField(max_length=4, verbose_name='Jahr der Produkt')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes', verbose_name='Fotografie')),
                ('precio', models.IntegerField(blank=True, null=True, verbose_name='Precio')),
                ('estado', models.CharField(choices=[('disponible', 'disponible'), ('no disponible', 'no disponible')], default='disponible', max_length=20, verbose_name='Estado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria', verbose_name='Kategorie')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='idProducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.producto', verbose_name='idProducto'),
        ),
        migrations.CreateModel(
            name='BoletaDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='idBoletaDetalle')),
                ('cantidad', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Cantidad')),
                ('idBoleta', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.boleta', verbose_name='idBoleta')),
                ('idProducto', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.producto', verbose_name='idProducto')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='idVenta')),
                ('idCompra', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.compra', verbose_name='idCompra')),
            ],
        ),
    ]
