# Generated by Django 5.2.1 on 2025-05-11 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_balancemensual_informedesemp_informemensual_tipouser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boleta',
            old_name='idUser',
            new_name='usuario',
        ),
    ]
