# Generated by Django 5.2.1 on 2025-05-11 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_iduser_boleta_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancemensual',
            old_name='BalancesMensual',
            new_name='BalanceMensual',
        ),
    ]
