# Generated by Django 5.2.1 on 2025-05-12 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_rename_balancesmensual_balancemensual_balancemensual'),
    ]

    operations = [
        migrations.CreateModel(
            name='preview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='idPreview')),
                ('cantidad', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Cantidad')),
                ('total', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Total')),
                ('fecha', models.DateTimeField(null=True, verbose_name='Fecha')),
                ('idUser', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='idUserr')),
            ],
        ),
    ]
