# Generated by Django 5.2.1 on 2025-05-12 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preview',
            name='fecha',
        ),
    ]
