# Generated by Django 5.2.1 on 2025-05-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_preview_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='preview',
            name='name',
            field=models.CharField(default='no user', max_length=50, verbose_name='name'),
        ),
    ]
