# Generated by Django 5.2.1 on 2025-05-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_compra_cantidad_remove_compra_idproducto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
