# Generated by Django 5.2.1 on 2025-05-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_boleta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletadetalle',
            name='totalPorItem',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='TotalPorItem'),
        ),
    ]
