# Generated by Django 5.2.1 on 2025-05-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_boletadetalle_totalporitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletadetalle',
            name='nombre',
            field=models.CharField(default='no user', max_length=50, verbose_name='Nombre'),
        ),
    ]
