# Generated by Django 5.2.1 on 2025-05-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_boletadetalle_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('enviado', 'enviado'), ('entregado', 'entregado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
