# Generated by Django 5.2.1 on 2025-05-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_compra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Cantidad'),
        ),
    ]
