# Generated by Django 5.2.1 on 2025-05-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_compra_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tipo',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Vendedor', 'Vendedor'), ('Bodeguero', 'Bodeguero'), ('Contador', 'Contador'), ('Administrador', 'Administrador')], default='Cliente', max_length=20, verbose_name='Tipo de Usuario'),
        ),
    ]
