# Generated by Django 5.2.1 on 2025-05-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion'),
        ),
    ]
