# Generated by Django 5.2.1 on 2025-05-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_pedido_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicacion'),
        ),
    ]
