# Generated by Django 5.2.1 on 2025-05-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_producto_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancemensual',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
