# Generated by Django 5.2.1 on 2025-05-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_balancemensual_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(default='Pagado', max_length=20, verbose_name='Estado'),
        ),
    ]
