# Generated by Django 5.2.1 on 2025-05-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_compra_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(default='Nombre Sucursal', max_length=40, verbose_name='Nombre')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion')),
            ],
        ),
    ]
