# Generated by Django 5.2.1 on 2025-05-15 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('length', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Longitud')),
                ('width', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Ancho')),
                ('height', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Altura')),
                ('weight', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Peso')),
                ('idPedido', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.compra', verbose_name='idPedido')),
            ],
        ),
    ]
