# Generated by Django 5.2.1 on 2025-05-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_paquete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre')),
                ('street', models.CharField(blank=True, max_length=40, null=True, verbose_name='Calle')),
                ('city', models.CharField(blank=True, max_length=40, null=True, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=40, null=True, verbose_name='Region')),
                ('zipcode', models.CharField(blank=True, max_length=40, null=True, verbose_name='Codigo Postal')),
                ('country', models.CharField(blank=True, max_length=40, null=True, verbose_name='Pais')),
                ('phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='Numero')),
            ],
        ),
    ]
