# Generated by Django 5.2.1 on 2025-05-15 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_direccion_iduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
    ]
