# Generated by Django 5.2.1 on 2025-05-16 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_preview_iddireccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='idDireccion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.direccion', verbose_name='idDireccion'),
        ),
    ]
