# Generated by Django 5.2.1 on 2025-05-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_boleta_iddireccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='name',
            field=models.CharField(default='', max_length=40, verbose_name='Nombre'),
        ),
    ]
