# Generated by Django 5.2.1 on 2025-05-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_pedido_iddireccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='address',
        ),
    ]
