# Generated by Django 5.2.1 on 2025-05-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_remove_pedido_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='distance_unit',
            field=models.CharField(default='in', max_length=5, verbose_name='Unidad de distancia'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='mass_unit',
            field=models.CharField(default='lb', max_length=5, verbose_name='Unidad de masa'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Ancho'),
        ),
    ]
