# Generated by Django 5.2.1 on 2025-05-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_paquete_idpedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='distance_unit',
            field=models.CharField(default='cm', max_length=5, verbose_name='Unidad de distancia'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='mass_unit',
            field=models.CharField(default='kg', max_length=5, verbose_name='Unidad de masa'),
        ),
    ]
