# Generated by Django 5.2.1 on 2025-05-17 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_paquete_distance_unit_alter_paquete_mass_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='idPedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pedido', verbose_name='idPedido'),
        ),
    ]
