# Generated by Django 5.2.1 on 2025-05-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_paquete_idpedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='estado',
            field=models.CharField(choices=[('entregado', 'Entregado'), ('pendiente', 'pendiente')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
