# Generated by Django 5.2.1 on 2025-05-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_paquete_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slogan',
            field=models.TextField(blank=True, null=True, verbose_name='slogan'),
        ),
    ]
