# Generated by Django 5.2.1 on 2025-05-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_customuser_slogan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='slogan',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default='', null=True, verbose_name='biografia'),
        ),
    ]
