# Generated by Django 5.2.1 on 2025-05-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_remove_customuser_slogan_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='sent'),
        ),
    ]
