# Generated by Django 5.2.1 on 2025-05-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_compra_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='sent'),
        ),
    ]
