# Generated by Django 5.2.1 on 2025-05-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_pedido_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='sent',
        ),
        migrations.AddField(
            model_name='compra',
            name='created',
            field=models.BooleanField(default=False, verbose_name='created'),
        ),
    ]
