# Generated by Django 5.2.1 on 2025-05-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_remove_compra_sent_compra_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informedesemp',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
