# Generated by Django 5.2.1 on 2025-05-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_informedesemp_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informedesemp',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='FechaInformeDesemp'),
        ),
    ]
