# Generated by Django 5.2.1 on 2025-05-21 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_informedesemp_iduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='informemensual',
            name='idUser',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='idUser'),
        ),
        migrations.AlterField(
            model_name='informemensual',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='informemensual',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='FechaInformeMensual'),
        ),
    ]
