# Generated by Django 5.2.1 on 2025-05-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_remove_balancemensual_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='idGasto')),
                ('total', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Total')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
        ),
        migrations.AlterField(
            model_name='balancemensual',
            name='gastos',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Gastos'),
        ),
    ]
