# Generated by Django 5.2.1 on 2025-05-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_gasto_alter_balancemensual_gastos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total'),
        ),
    ]
