# Generated by Django 5.2.1 on 2025-05-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_alter_gasto_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total'),
        ),
    ]
